name: index_safe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - gdal
  - boto3
  - indexed_gzip
  - tqdm
  - numpy
  - pandas
  - requests
  - fsspec
  - s3fs
  - aiohttp
  # For packaging, and testing
  - pytest
  - pip:
    - zran

