name: index_safe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - gdal
  - boto3
  - tqdm
  - numpy
  - requests
  # For packaging, and testing
  - pytest
  - pipreqs
  - pip:
    - zran

