AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates Sentinel-1 index files that are uploaded to a bucket
Parameters:
  DestinationBucketName:
    Type: String
Resources:
  ## S3 bucket
  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DestinationBucketName 
  ## Lambda function
  IndexCreationFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ['create_index.lambda_handler']
      Timeout: 900
      MemorySize: 10240
      EphemeralStorage:
        Size: 10240
      Architectures:
        - x86_64
      Environment:
        Variables:
          DestinationBucketName: !Ref DestinationBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DestinationBucketName
